---
title: "POMA: An R Package for Statistical Analysis of Metabolomic Data"
author: "Pol Castellano-Escuder"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{POMA: An R Package for Statistical Analysis of Metabolomic Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, eval = FALSE}
library(POMA)
```

```{r, eval = FALSE}
data <- vroom::vroom("../data_ST000284/MET_CRC_ST000284.csv", delim = ",")

imputed <- PomaImpute(data, ZerosAsNA = T, RemoveNA = T, method = "knn")

# norm_none <- PomaNorm(imputed, method = "none")
log_transformation_norm <- PomaNorm(imputed, method = "log_transformation")

# PomaNormPlot(norm_none)
PomaNormPlot(imputed)
PomaNormPlot(log_scaling_norm)
# PomaNormPlot(norm_none, group = "metabolites")
PomaNormPlot(imputed, group = "metabolites")
PomaNormPlot(log_scaling_norm, group = "metabolites")

univ_ttest <- PomaUnivariate(log_transformation_norm, method = "ttest", adjust = "fdr")
# univ_mann <- PomaUnivariate(norm, method = "mann", adjust = "fdr")

PomaVolcano(univ_ttest, xlim = 0.15, FC_cutoff = 1.03)
# PomaVolcano(univ_mann, pval = "raw", Pval_cutoff = 0.05, FC_cutoff = 0.05, xlim = 2)

multiv_splsda <- PomaMultivariate(log_scaling_norm, method = c("splsda"), components = 5,
                                  validation = "Mfold", folds = 5, nrepeat = 10, 
                                  num_features = 10)
multiv_splsda$selected_variables
multiv_splsda$splsda_scores_plot
```

